# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 19:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linearid', models.CharField(max_length=22)),
                ('fullname', models.CharField(max_length=100)),
                ('rttyp', models.CharField(max_length=1)),
                ('mtfcc', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
