# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 19:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statefp', models.CharField(max_length=2)),
                ('unsdlea', models.CharField(max_length=5)),
                ('geoid', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=100)),
                ('lsad', models.CharField(max_length=2)),
                ('lograde', models.CharField(max_length=2)),
                ('higrade', models.CharField(max_length=2)),
                ('mtfcc', models.CharField(max_length=5)),
                ('sdtyp', models.CharField(max_length=1)),
                ('funcstat', models.CharField(max_length=1)),
                ('aland', models.FloatField()),
                ('awater', models.FloatField()),
                ('intptlat', models.CharField(max_length=11)),
                ('intptlon', models.CharField(max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=-1)),
            ],
        ),
    ]
