# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_schooldistrict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooldistrict',
            old_name='unsdlea',
            new_name='lea',
        ),
    ]
