# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 23:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20160708_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldistrict',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=-1),
        ),
    ]
