# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20160708_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncessch', models.IntegerField()),
                ('stateFips', models.IntegerField()),
                ('leaid', models.IntegerField()),
                ('schno', models.IntegerField()),
                ('stid', models.IntegerField()),
                ('seasch', models.IntegerField()),
                ('lea', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('zipcode4', models.IntegerField()),
                ('schooltype', models.IntegerField()),
                ('status', models.IntegerField()),
                ('locale', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('countyid', models.IntegerField()),
                ('county', models.CharField(max_length=50)),
                ('teachers', models.FloatField()),
                ('gradeLow', models.CharField(max_length=5)),
                ('gradeHigh', models.CharField(max_length=5)),
                ('students', models.IntegerField()),
                ('ratio', models.FloatField()),
            ],
        ),
    ]
