# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='ncessch',
        ),
        migrations.RemoveField(
            model_name='school',
            name='ratio',
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='seasch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='stid',
            field=models.CharField(max_length=20),
        ),
    ]
