# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20160710_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='county',
        ),
        migrations.RemoveField(
            model_name='school',
            name='countyid',
        ),
        migrations.RemoveField(
            model_name='school',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='school',
            name='schooltype',
        ),
        migrations.RemoveField(
            model_name='school',
            name='seasch',
        ),
        migrations.RemoveField(
            model_name='school',
            name='stateFips',
        ),
        migrations.RemoveField(
            model_name='school',
            name='status',
        ),
        migrations.RemoveField(
            model_name='school',
            name='stid',
        ),
        migrations.RemoveField(
            model_name='school',
            name='students',
        ),
        migrations.RemoveField(
            model_name='school',
            name='teachers',
        ),
    ]
