# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20160710_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='leaid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='schno',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='zipcode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='zipcode4',
            field=models.BigIntegerField(),
        ),
    ]
