# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_remove_school_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.SchoolDistrict'),
        ),
    ]
