# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:26
from __future__ import unicode_literals
from django.contrib.gis.geos import Point
from django.db import migrations,models


class Migration(migrations.Migration):
    def setLocation(apps,schema_editor):
        School = apps.get_model('map','School')
        for s in School.objects.all():
            try:
                s.location=Point(s.lng,s.lat)
                s.save()
            except:
                print 'ERROR: %s'%s

    dependencies = [
        ('map', '0013_school_location'),
    ]

    operations = [
        migrations.RunPython(setLocation)
    ]
